### ISSUE TITLE
representative_piece

### ISSUE THREAD

**Issue by IanaKhitsko** [auvy/mipz_2023#6]
https://github.com/auvy/mipz_2023/blob/235417fbe112887a4f55b1f9883d0b57bc109f3c/lab1/src/map.py#LL56C14-L56C14

Why?? Why do you pass money to return it?

**Comment by auvy** [comment]
it's not necessary for this function to even exist 
but i thought it'd be better to just have a formula readily available in case a change is needed or something 
if you think it's not needed i'll just remove it
