### ISSUE TITLE
Keep assigning bool value

### ISSUE THREAD

**Issue by IanaKhitsko** [auvy/mipz_2023#7]
https://github.com/auvy/mipz_2023/blob/235417fbe112887a4f55b1f9883d0b57bc109f3c/lab1/src/validity.py#LL70C9-L70C18
 why do you do this multiple times? Why not break the cycle? Or if you need to check all neighbors to be true, you'll need another approach.

**Comment by auvy** [comment]
oh yeah i forgot to add a break my bad thx for noticing
